### ISSUE TITLE
Do we still need to wait for Gatling 2.2.0

### ISSUE THREAD

**Issue by ghost** [constantijn/gatling-funtest-example#1]
To use GatlingFunSpec?

**Comment by constantijn** [comment]
How do you mean?
The code is in the 2.2.0 branch and it won't work without the code ;)
I tried it with Gatling 2.2.0-M3 the other day and it worked fine.

There's nothing gatling 2.2.0 specific it depends on, so if your question is can we cherry-pick it to 2.1.x i don't see why not.

**Comment by ghost** [comment]
OK. Got it. I didn't think this functionality was a part of 2.2.0. Although we are currently on 2.17. Thanks.
