### ISSUE TITLE
Move this respository to the Gatling organization?

### ISSUE THREAD

**Issue by zoosky** [constantijn/gatling-funtest-example#3]
Hi @constantijn 

What do you think of Stéphanes proposal?

See https://groups.google.com/d/msg/gatling/Oy9B3KvOjoQ/RkrDn4ZVBAAJ

FunSpec is probably something that we'll want to improve for Gatling 3. Suggestions welcome!

Then, do you think it would be possible to move this repository to the Gatling organization?
I would feel more comfortable if our documentation didn't point to external resources (can't bet on what could happen in the future, like the repo being removed). We already have a sbt demo project and a maven demo project, and it would make sense to have this one alongside.
WDYT?

Stéphane Landelle
GatlingCorp CEO

**Comment by constantijn** [comment]
Sounds good. I'll submit a ticket to github asking them to move the project to the Gatling repos

Sent from my iPad

On 23 aug. 2016, at 12:43, "Andreas Kapp" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @constantijnhttps://github.com/constantijn

What do you think of St?phanes proposal?

See https://groups.google.com/d/msg/gatling/Oy9B3KvOjoQ/RkrDn4ZVBAAJ

FunSpec is probably something that we'll want to improve for Gatling 3. Suggestions welcome!

Then, do you think it would be possible to move this repository to the Gatling organization?
I would feel more comfortable if our documentation didn't point to external resources (can't bet on what could happen in the future, like the repo being removed). We already have a sbt demo project and a maven demo project, and it would make sense to have this one alongside.
WDYT?

St?phane Landelle
GatlingCorp CEO

##

**Comment by constantijn** [comment]
Seems i need admin access on gatling to transfer the repo there automatically. Have a ticket in with github now asking them on how to transfer the repo without needing admin access.

(Making the assumption here you guys would prefer not to hand over admin access.)

**Comment by zoosky** [comment]
Great, thx

**Comment by slandelle** [comment]
Hey.

Yeah, sorry, we really can't give you temporary admin access on the Gatling organisation.

If Github can't let us transfer the repository, we can just push a clone.
That's what I've done here: https://github.com/gatling/gatling-funspec-demo (I haven't made it "official" yet, waiting for your approval).
We'd keep all the commit history, but we'd lose the bugtracker (that only contains this one).

WDYT?

**Comment by constantijn** [comment]
Looks goot to me
(sorry for the late reply)

**Comment by slandelle** [comment]
Awesome, thanks!
I'd like to mention you as the the original author in our doc. What's your real name?

**Comment by slandelle** [comment]
Done, thanks a bunch!
http://gatling.io/docs/2.2.2/general/functional_specs.html

**Comment by constantijn** [comment]
Constantijn Visinescu :)

**Comment by slandelle** [comment]
Updated :)

**Comment by zoosky** [comment]
Great news
